name: main
on: [workflow_dispatch]
jobs:
  buildlinux:
    runs-on: [ubuntu-latest]
    steps:
      - name: checkout
        uses: actions/checkout@main
      - name: install haxe
        uses: krdlab/setup-haxe@master
        with:
          haxe-version: 4.3.4
      - name: install library
        run: |
          haxelib git hxcpp https://github.com/mcagabe19-stuff/hxcpp
          haxelib install hxnodejs
          haxelib git lime https://github.com/mcagabe19-stuff/lime
          haxelib install openfl
          haxelib install flixel 4.11.0
          haxelib install hscript
          haxelib install flixel-ui
          haxelib install flixel-addons 2.11.0
          haxelib install newgrounds 1.4.0
          haxelib git faxe https://github.com/ashea-code/faxe
          haxelib git extension-androidtools https://github.com/MAJigsaw77/extension-androidtools/
          haxelib install polymod 1.3.1
      - name: add APIStuff
        run: echo "package;class APIStuff{public static var API:String = '';public static var EncKey:String = '';}" > source/APIStuff.hx
      - name: Configure Android
        run: |
          haxelib run lime config ANDROID_SDK $ANDROID_HOME
          haxelib run lime config ANDROID_NDK_ROOT $ANDROID_NDK_LATEST_HOME
          haxelib run lime config JAVA_HOME $JAVA_HOME_17_X64
          haxelib run lime config ANDROID_SETUP true
      - name: compile
        run: haxelib run lime build android
      - name: upload artifact
        uses: actions/upload-artifact@main
        with:
          name: buildmobile
          path: export/release/android/bin/app/build/outputs/apk/debug
